export const ORDER_SELECT_NUMERICAL = "ORDER_SELECT_NUMERICAL";
export const ORDER_SELECT_ATOZ = "ORDER_SELECT_ATOZ";
export const ORDER_SELECT_TALLEST = "ORDER_SELECT_TALLEST";
export const ORDER_SELECT_SMALLEST = "ORDER_SELECT_SMALLEST";
export const ORDER_SELECT_HEAVIEST = "ORDER_SELECT_HEAVIEST";
export const ORDER_SELECT_LIGHTEST = "ORDER_SELECT_LIGHTEST";
export const ORDER_SELECT_RESET = "ORDER_SELECT_RESET";

export const NAME_SELECT_A = "NAME_SELECT_A";
export const NAME_SELECT_B = "NAME_SELECT_B";
export const NAME_SELECT_C = "NAME_SELECT_C";
export const NAME_SELECT_D = "NAME_SELECT_D";
export const NAME_SELECT_E = "NAME_SELECT_E";
export const NAME_SELECT_F = "NAME_SELECT_F";
export const NAME_SELECT_G = "NAME_SELECT_G";
export const NAME_SELECT_H = "NAME_SELECT_H";
export const NAME_SELECT_I = "NAME_SELECT_I";
export const NAME_SELECT_J = "NAME_SELECT_J";
export const NAME_SELECT_K = "NAME_SELECT_K";
export const NAME_SELECT_L = "NAME_SELECT_L";
export const NAME_SELECT_M = "NAME_SELECT_M";
export const NAME_SELECT_N = "NAME_SELECT_N";
export const NAME_SELECT_O = "NAME_SELECT_O";
export const NAME_SELECT_P = "NAME_SELECT_P";
export const NAME_SELECT_Q = "NAME_SELECT_Q";
export const NAME_SELECT_R = "NAME_SELECT_R";
export const NAME_SELECT_S = "NAME_SELECT_S";
export const NAME_SELECT_T = "NAME_SELECT_T";
export const NAME_SELECT_U = "NAME_SELECT_U";
export const NAME_SELECT_V = "NAME_SELECT_V";
export const NAME_SELECT_W = "NAME_SELECT_W";
export const NAME_SELECT_X = "NAME_SELECT_X";
export const NAME_SELECT_Y = "NAME_SELECT_Y";
export const NAME_SELECT_Z = "NAME_SELECT_Z";
export const NAME_SELECT_DASH = "NAME_SELECT_DASH";
export const NAME_SELECT_RESET = "NAME_SELECT_RESET";

export const FORM_SELECT_HEAD = "NAME_SELECT_HEAD";
export const FORM_SELECT_SERPENTINEBODY = "FORM_SELECT_SERPENTINEBODY";
export const FORM_SELECT_FINS = "FORM_SELECT_FINS";
export const FORM_SELECT_HEADANDARMS = "NAME_SELECT_HEADANDARMS";
export const FORM_SELECT_HEADANDBASE = "NAME_SELECT_HEADANDBASE";
export const FORM_SELECT_BIPEDALTAILEDFORM = "FORM_SELECT_BIPEDALTAILEDFORM";
export const FORM_SELECT_HEADANDLEGS = "NAME_SELECT_HEADANDLEGS";
export const FORM_SELECT_QUADRUPEDBODY = "NAME_SELECT_QUADRUPEDBODY";
export const FORM_SELECT_SINGLEPAIROFWINGS = "FORM_SELECT_SINGLEPAIROFWINGS";
export const FORM_SELECT_TENTACLESORMULTIPEDBODY = "FORM_SELECT_TENTACLESORMULTIPEDBODY";
export const FORM_SELECT_MULTIPLEBODIES = "NAME_SELECT_MULTIPLEBODIES";
export const FORM_SELECT_BIPEDALTAILLESSFORM = "FORM_SELECT_BIPEDALTAILLESSFORM";
export const FORM_SELECT_TWOORMOREPAIRSOFWINGS = "FORM_SELECT_TWOORMOREPAIRSOFWINGS";
export const FORM_SELECT_INSECTOIDBODY = "FORM_SELECT_INSECTOIDBODY";
export const FORM_SELECT_BLANKENTRY = "FORM_SELECT_BLANKENTRY";
export const FORM_SELECT_RESET = "FORM_SELECT_RESET";

export const TYPE_SELECT_NORMAL = "TYPE_SELECT_NORMAL";
export const TYPE_SELECT_GROUND = "TYPE_SELECT_GROUND";
export const TYPE_SELECT_STEEL = "TYPE_SELECT_STEEL";
export const TYPE_SELECT_ELECTRIC = "TYPE_SELECT_ELECTRIC";
export const TYPE_SELECT_DARK = "TYPE_SELECT_DARK";
export const TYPE_SELECT_FIGHT = "TYPE_SELECT_FIGHT";
export const TYPE_SELECT_ROCK = "TYPE_SELECT_ROCK";
export const TYPE_SELECT_FIRE = "TYPE_SELECT_FIRE";
export const TYPE_SELECT_PSYCHIC = "TYPE_SELECT_PSYCHIC";
export const TYPE_SELECT_DASHES = "TYPE_SELECT_DASHES";
export const TYPE_SELECT_FLYING = "TYPE_SELECT_FLYING";
export const TYPE_SELECT_BUG = "TYPE_SELECT_BUG";
export const TYPE_SELECT_WATER = "TYPE_SELECT_WATER";
export const TYPE_SELECT_ICE = "TYPE_SELECT_ICE";
export const TYPE_SELECT_POISON = "TYPE_SELECT_POISON";
export const TYPE_SELECT_GHOST = "TYPE_SELECT_GHOST";
export const TYPE_SELECT_GRASS = "TYPE_SELECT_GRASS";
export const TYPE_SELECT_DRAGON = "TYPE_SELECT_DRAGON";
export const TYPE_SELECT_RESET = "TYPE_SELECT_RESET";




