export const ORDER_SELECT_NUMERICAL = "ORDER_SELECT_NUMERICAL";
export const ORDER_SELECT_ATOZ = "ORDER_SELECT_ATOZ";
export const ORDER_SELECT_TALLEST = "ORDER_SELECT_TALLEST";
export const ORDER_SELECT_SMALLEST = "ORDER_SELECT_SMALLEST";
export const ORDER_SELECT_HEAVIEST = "ORDER_SELECT_HEAVIEST";
export const ORDER_SELECT_LIGHTEST = "ORDER_SELECT_LIGHTEST";
export const ORDER_SELECT_RESET = "ORDER_SELECT_RESET";

export const NAME_SELECT_A = "NAME_SELECT_A";
export const NAME_SELECT_B = "NAME_SELECT_B";
export const NAME_SELECT_C = "NAME_SELECT_C";
export const NAME_SELECT_D = "NAME_SELECT_D";
export const NAME_SELECT_E = "NAME_SELECT_E";
export const NAME_SELECT_F = "NAME_SELECT_F";
export const NAME_SELECT_G = "NAME_SELECT_G";
export const NAME_SELECT_H = "NAME_SELECT_H";
export const NAME_SELECT_I = "NAME_SELECT_I";
export const NAME_SELECT_J = "NAME_SELECT_J";
export const NAME_SELECT_K = "NAME_SELECT_K";
export const NAME_SELECT_L = "NAME_SELECT_L";
export const NAME_SELECT_M = "NAME_SELECT_M";
export const NAME_SELECT_N = "NAME_SELECT_N";
export const NAME_SELECT_O = "NAME_SELECT_O";
export const NAME_SELECT_P = "NAME_SELECT_P";
export const NAME_SELECT_Q = "NAME_SELECT_Q";
export const NAME_SELECT_R = "NAME_SELECT_R";
export const NAME_SELECT_S = "NAME_SELECT_S";
export const NAME_SELECT_T = "NAME_SELECT_T";
export const NAME_SELECT_U = "NAME_SELECT_U";
export const NAME_SELECT_V = "NAME_SELECT_V";
export const NAME_SELECT_W = "NAME_SELECT_W";
export const NAME_SELECT_X = "NAME_SELECT_X";
export const NAME_SELECT_Y = "NAME_SELECT_Y";
export const NAME_SELECT_Z = "NAME_SELECT_Z";
export const NAME_SELECT_DASH = "NAME_SELECT_DASH";
export const NAME_SELECT_RESET = "NAME_SELECT_RESET";


