export const ORDER_SELECT_NUMERICAL = "ORDER_SELECT_NUMERICAL";
export const ORDER_SELECT_ATOZ = "ORDER_SELECT_ATOZ";
export const ORDER_SELECT_TALLEST = "ORDER_SELECT_TALLEST";
export const ORDER_SELECT_SMALLEST = "ORDER_SELECT_SMALLEST";
export const ORDER_SELECT_HEAVIEST = "ORDER_SELECT_HEAVIEST";
export const ORDER_SELECT_LIGHTEST = "ORDER_SELECT_LIGHTEST";
